# Generated by Django 3.1.2 on 2020-10-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
